### ISSUE TITLE
Questions about the Null_value

### ISSUE THREAD

**Issue by pyli0628** [snap-stanford/pretrain-gnns#16]
Hi,
Thanks for this impressive work! I just want to know the details about how you deal with the datasets with null value when the datasets were split for finetune, such as MUV and ToxCast. It seems that you filled the NULL values with 0 in your [finetune.py](https://github.com/snap-stanford/pretrain-gnns/blob/master/chem/finetune.py), but it would add new labels (0) into the dataset if you filled NULL with 0,  whether it should fill with other values except 0 and 1? Correct me if I am wrong.
Thanks again!

**Comment by pyli0628** [comment]
Sorry for interrupt. It seems that your labels are -1 and 1, so fill null value with 0 would not add new labels, right?  Another question is :  which split method did you use in your paper, scaffold or random scaffold ?

**Comment by weihua916** [comment]
That't right. We use +1 or -1, and we ignore 0 during training and testing.
We always used scaffold.

**Comment by pyli0628** [comment]
Sorry to bother you again. I wonder whether to mask the edges in your masking pre-trained model for molecules ('chem/model_gin/masking.pth)? I wonder if it improves the performance when mask edges together with atoms.  Thanks again!

**Comment by weihua916** [comment]
In our preliminary experiments, we did not observe much gain by masking edges.

**Comment by gr986** [comment]
I have a question. Is the y_true.shape=torch.Size([1])？
if so, I return to the following question In this line:
 y_true.append(batch.y.view(pred.shape)):


RuntimeError: shape '[1, 300]' is invalid for input of size 1
