### ISSUE TITLE
sufficient GPU

### ISSUE THREAD

**Issue by badtom** [snap-stanford/pretrain-gnns#17]
Could you please let me know what GPU you used to run your experiments (in your publication and on https://openreview.net/forum?id=HJlWWJSFDH computation times for a single GPU implementation are mentioned
but I could not find information on what GPU was used). More generally, do you know what GPU memory would be sufficient
to run your experiments - e.g.  would GeForce RTX 2080 Ti with 11 GB be enough?

**Comment by weihua916** [comment]
We used GeForce RTX 2080 (11GB GPU).

**Comment by badtom** [comment]
Thanks a lot for your answer.
