### ISSUE TITLE
Questions about ChEMBL Loader

### ISSUE THREAD

**Issue by chao1224** [snap-stanford/pretrain-gnns#19]
Hi there,
Got two questions about the function [`_load_chembl_with_labels_dataset `](https://github.com/snap-stanford/pretrain-gnns/blob/master/chem/loader.py#L1179):

1. I am wondering why you generate isomeric SMILES from Molecule and then choose the largest one? Didn't find this in the original [loader file](https://github.com/ml-jku/lsc/blob/master/pythonCode/lstm/loadData.py). Is there any specific reason for doing this?
2. What's the difference with the above generated smiles with the one stored in `chembl20Smiles.pckl`?

Any help would be appreciated.

**Comment by weihua916** [comment]
I think the difference is subtle. My guess is that we just wanted to standardize the SMILES expression.

**Comment by chao1224** [comment]
I see. Thanks.
