### ISSUE TITLE
Questions about rou_auc value

### ISSUE THREAD

**Issue by JiangOfCHINA** [snap-stanford/pretrain-gnns#20]
Hi,
Thanks for this impressive work! I just want to know the details about how you get rou_auc value. Does the following code calculate the AUC value on the test set.
![image](https://user-images.githubusercontent.com/50139431/87849127-abfb6980-c918-11ea-9104-8ebd2310ec1f.png)

Any help would be appreciated.

**Comment by weihua916** [comment]
Correct!

**Comment by JiangOfCHINA** [comment]
Thank you so much!
