### ISSUE TITLE
Question about OGB submission

### ISSUE THREAD

**Issue by agamemnonc** [snap-stanford/pretrain-gnns#22]
Hi there,

I was just wondering whether you have used the pre-training strategies proposed in the paper for your submissions in OGB, e.g. when training the GIN+virtual node models for `molpcba` and `molhiv`datasets, as described [here](https://github.com/snap-stanford/ogb/tree/master/examples/graphproppred/mol).

Thanks!

**Comment by weihua916** [comment]
Those are trained from scratch on the given dataset, no pre-training.

**Comment by agamemnonc** [comment]
Thanks for the reply.
