### ISSUE TITLE
Docker for running code?

### ISSUE THREAD

**Issue by cyrusmaher** [snap-stanford/pretrain-gnns#23]
Hi Weihua, I love your pre-training paper, and I'm looking forward to trying out the code. I tried installing the particular library versions that you list, but I can't get `torch-scatter==1.1.2` to install. Could you share a docker file or image to run the code? I anticipate this would help others as well. Thanks for your help!

**Comment by holoword** [comment]
> Hi Weihua, I love your pre-training paper, and I'm looking forward to trying out the code. I tried installing the particular library versions that you list, but I can't get `torch-scatter==1.1.2` to install. Could you share a docker file or image to run the code? I anticipate this would help others as well. Thanks for your help!

Maybe you can download from torch-scatter GitHub release page, and use pip install the package! Meanwhile, I agree with the docker image which is a good choice to reproduce the results!

**Comment by cyrusmaher** [comment]
Yes, I did try pip install, but there were incompatible dependencies. Seems solvable with a separate conda environment if the docker image is not convenient.

**Comment by mdanb** [comment]
@cyrusmaher did you create the image by any chance?
