### ISSUE TITLE
Question about code of supervised pre-training on Chem dataset

### ISSUE THREAD

**Issue by hyp1231** [snap-stanford/pretrain-gnns#36]
Hi, thanks for the amazing work!
I have a question about code of supervised pre-training on Chem dataset.

https://github.com/snap-stanford/pretrain-gnns/blob/7bb81b5cc2d37241ee72cbfa40fbd89b0cc2394f/chem/pretrain_supervised.py#L14-L15

I wonder what's the differences between `model` and `model_extra`, or could you please share the code of `model_extra`?

Thanks!

**Comment by weihua916** [comment]
Hi! Apologies, I forgot to clean up that part. I checked my private code that I used for running experiments and the `model_extra` is exactly the same as the current `model`. I fixed it in the master branch.

**Comment by hyp1231** [comment]
Got it, thanks!

**Comment by hyp1231** [comment]
一
