### ISSUE TITLE
License for Code

### ISSUE THREAD

**Issue by rbharath** [snap-stanford/pretrain-gnns#4]
Thanks for releasing this code! I really like your paper and am excited to try it out in some of my projects :)

Would it be possible to add a LICENSE for this repo? If you folks are unsure what license would be good, I'd suggest MIT (flexible, friendly for many use cases).

**Comment by weihua916** [comment]
Sure, I just added MIT LICENSE!

**Comment by rbharath** [comment]
Thanks! Much appreciated :)
