### ISSUE TITLE
Could you share the entire package list? Thanks!

### ISSUE THREAD

**Issue by yuzhenmao** [snap-stanford/pretrain-gnns#45]
Thanks for the amazing paper and code! However, we found it is hard to establish the environment since the packages listed in README seem too old or incompatible with our CUDA version. We try to use torch==1.7.0, and torch-sparse/cluster/scatter listed here (https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html), which is compatible with our CUDA==11.0, but cannot train the model and has this error: 

ValueError: `MessagePassing.propagate` only supports `torch.LongTensor` of shape `[2, num_messages]` or `torch_sparse.SparseTensor` for argument `edge_index`.

Could you please share the conda package list with us, including the CUDA version? Thanks!

**Comment by leibohan** [comment]
你最后怎么解决的这个问题，是改了包吗？
