### ISSUE TITLE
Some questions about bio.  dataset.

### ISSUE THREAD

**Issue by rootlu** [snap-stanford/pretrain-gnns#7]
Hi,

The paper said that 394,925 protein subgraphs are used for the self-supervised pre-training, but the code only loads 306,925 subgraphs (without 88000 labeled subgraphs?).

So, how many graphs used in the pre-trained models?  
I am wondering whether I lose any insight behind that.

**Comment by weihua916** [comment]
Hi, thank you for pointing out. I double-checked it, and found out that the number of unlabeled subgraphs is indeed 306925, not 394925 (as mentioned in the paper). Our experimental results are still obtained on the provided unlabeled graphs.

**Comment by rootlu** [comment]
Thx.
