### ISSUE TITLE
ImportError and RuntimeError 

### ISSUE THREAD

**Issue by JiangOfCHINA** [snap-stanford/pretrain-gnns#8]
Hellos and thanks for sharing.Some errors occurred while running the program.

ImportError: cannot import name 'segment_csr' from 'torch_scatter'(torch-cluster ==1.2.4)

RuntimeError: scatter_add() expected at most 5 argument(s) but received 6 argument(s). Declaration: scatter_add(Tensor src, Tensor index, int dim=-1, Tensor? out=None, int? dim_size=None) -> (Tensor)(torch-scatter==2.0.4)

I don't know how to solve it. I look forward to receiving your reply.

**Comment by weihua916** [comment]
Did you make sure the package versions are all the same as indicated in the README.md? If so, please paste your other package versions.

**Comment by JiangOfCHINA** [comment]
Thanks your reply.One package version is different as requirements because of my carelessness.
