### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by yyou1996** [snap-stanford/pretrain-gnns#9]
Hi,

Great job! I have a minor question. When running code, I got the following error (the package version should be correct as readme).

`ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version CXXABI_1.3.11 not found (required by /home/tlchen/anaconda3/envs/gnnrdkit/lib/python3.6/site-packages/rdkit/DataStructs/../../../../libRDKitDataStructs.so.1)`

How to solve this? Thank you!

**Comment by weihua916** [comment]
Hi! The issue seems to be related to your own environment.
